Creating work-section and about-me section
The-Normal-One1/PortFolio pull request #2
Opened 2022-09-23 15:27 UTC by The-Normal-One1

I tried the replicate the Figma homepage for template 2 using HTML and CSS with the help of VS-code.

2022-09-23 17:04 UTC, GiuseppeTG requested changes
Hi @The-Normal-One1  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif)

## Highlights
✅ Nice first approach 👍 
✅ No linter errors
✅ Good documentation

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 17:04 UTC, GiuseppeTG commented on my_portfolio.html
> +    <section class="works">
- [x] The section "works" should wrap up all your project cards and it should use display: grid. Each of your project cards should not be a section tag. It can be, for example, a div with class="project-card" and use flexbox. 👍 

## Project requirement:
![Captura de Pantalla 2022-09-23 a la(s) 11 32 11 a  m](https://user-images.githubusercontent.com/86022690/192009095-cb0b41f6-775a-4f26-8269-9aa444c84777.png)

You can read [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout#:~:text=already%20be%20using.-,Grid%20and%20flexbox,columns%20at%20the%20same%20time.) more info about this topic. 🤓

2022-09-23 17:04 UTC, GiuseppeTG commented on my_portfolio.html
> +        <p class="my-recent">My Recent Works</p> <hr>
- [x] As this is a section title I suggest you use an `h2` tag for it, this is for semantic reasons. Browsers give more relevance to this type of tag when you are searching for something in, for example, google. 🤓

2022-09-23 17:04 UTC, GiuseppeTG commented on my_portfolio.html
> +        <h2 class="heading-content">Profesional Art <br> Printing Data</h2>
[OPTIONAL] Here you have a better approach on what tag you should use. I suggest to use a more hierarchy structure.
- title -> h1
- subtitle (or section title) -> h2
- titles for cards inside sections -> h3

😄

2022-09-23 17:04 UTC, GiuseppeTG commented on style.css
> +  }
- [x] Try removing the `position: absolute`.  Add `display: block` at the top. Give it a height that matches the Figma template.
I hope this is the result you wanted 😄

2022-09-23 17:04 UTC, GiuseppeTG commented on my_portfolio.html
> +    <section class="about">
- [x] Kindly fix the position of the background image of this section so that it matches with the Figma template 😄

2022-09-23 17:04 UTC, GiuseppeTG commented on my_portfolio.html
> +        <a class="resume" href="#">Get My Resume</a> <hr>
- [x] This can also be a button or `a` tag with its corresponding behavior for hover and pressed 👍

2022-09-23 17:04 UTC, GiuseppeTG commented on my_portfolio.html
> +        </ul>
- [x] These elements should not be `a` tags as they don't have a link to something. They are just plain text informing what languages and technologies you use. 🤓 

There is also a problem with the alignment:
FIGMA: 
![Captura de Pantalla 2022-09-23 a la(s) 11 57 09 a  m](https://user-images.githubusercontent.com/86022690/192013537-46790287-382c-4fc0-8a8c-c03c425f7c6f.png)

YOURS: 
![Captura de Pantalla 2022-09-23 a la(s) 12 00 04 p  m](https://user-images.githubusercontent.com/86022690/192013715-bbc82a75-3dab-463c-85da-53cebfee33ba.png)

2022-09-23 17:07 UTC, GiuseppeTG commented
- [ ] This section:

![Captura de Pantalla 2022-09-23 a la(s) 11 47 58 a  m](https://user-images.githubusercontent.com/86022690/192014466-44b1597c-28b4-48c5-b7ed-e16e420e0a29.png)

Please pay attention to de margins or padding in the Figma design and try to imitate them as much as possible.
Also, this button is bigger and has not the text in the center 🤓 

Kindly make these improvements 👍

2022-09-23 17:09 UTC, GiuseppeTG commented
- [ ] Kindly change the name of your HTML file to index.html
This is a standard and browsers recognize to display this file. I was not able to see your project properly the first time because of this. 👀

2022-09-24 11:31 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @The-Normal-One1 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 11:33 UTC, The-Normal-One1 commented
Thanks

On Sat, 24 Sep 2022, 2:31 pm Tresor Sawasawa, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> STATUS: APPROVE ✔️ ✔️ 🍾
>
> Hi @The-Normal-One1 <https://github.com/The-Normal-One1>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉 👏 👏 💯
>
> [image: nodding-yes]
> <https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966>
> To highlight 🍾
>
>    - All linters are passing ✔️
>    - Good commit history ✔️
>    - Good PR description ✔️
>    - Your README file is professional ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
>
> *Feel free to leave any questions or comments in the PR thread if
> something is not 100% clear. Please ping me @tresorsawasawa
> <https://github.com/tresorsawasawa> when you comment so I can receive the
> notification or use slack with the same name.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/The-Normal-One1/PortFolio/pull/2#pullrequestreview-1119251987>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2WWKB36BMLP3VSM5YUTHI3V73RCHANCNFSM6AAAAAAQUCWJ5M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-24 11:41 UTC, merged